### ISSUE TITLE
Extracurricular content (iOS/Swift content) not available.

### ISSUE THREAD

**Issue by manimohans** [udacity/arkit-issues#1]

**Comment by manimohans** [comment]
In the FAQ, it was mentioned that iOS/Swift content will be present as extra-curricular content and vice-versa. It's not present in the current dashboard. Just wanted to bring it up.

**Comment by martinwilter** [comment]
Thanks for reporting this, @anjaneyarvadai. We are looking into it.

**Comment by martinwilter** [comment]
@anjaneyarvadai, you should now have access to the Learn ARKit with Swift content in the Extracurricular section of your Learn ARKit with Unity program.

Thanks again for reporting the issue.
