### ISSUE TITLE
MagicHats prefab issues

### ISSUE THREAD

**Issue by ghersigaston** [udacity/arkit-issues#12]

**Comment by ghersigaston** [comment]
I am trying to replace the hat Prefab with the bunny, but even if I delete the prefab, it still renders hats. The code only references the "prefabs" but it is not instantiated to the hats, can someone show me how to do the replacement of prefabs please? if I wanted to use this knowledge outside of the Magic Hats I couldn't and I don't want to carry on until I understand what is going on

**Comment by durant-udacity** [comment]
Hi Gaston, this doesn't seem to be an issue with the course but a difficulty with implementation. Please ask your mentor on slack for this kind of help (udacityardeveloper.slack.com)
