### ISSUE TITLE
Error in Lesson 2 section 8

### ISSUE THREAD

**Issue by dhorner** [udacity/arkit-issues#2]
In the following text you state both systems are Left Handed.  One I assume should be Right Handed.

Converting between ARKit and Unity Coordinate Systems
Another important point about Coordinate Systems is being able to convert between two different systems. This is especially important because Unity uses a left handed coordinate system, while ARKit uses a left handed one.

**Comment by dhorner** [comment]
Also just below that another error.

"Luckily for this, this is already provided by Unity in their library in the form of two functions:"

I think you mean "Luckily for us"

**Comment by martinwilter** [comment]
Thanks for reporting this, @dhorner. Both typos have been correct.
