### ISSUE TITLE
Please provide the arhittest script to complete magic hats so I can study it.

### ISSUE THREAD

**Issue by mazurick** [udacity/arkit-issues#4]

**Comment by martinwilter** [comment]
@mazurick The [ARHitTest.cs](https://github.com/udacity/arkit-unity-course-assets/blob/master/Assets/Udacity/MagicalHats/Scripts/ARHitTest.cs) script is already in the [course assets]( https://github.com/udacity/arkit-unity-course-assets) which is linked from the [Implementing Magical Hats](https://classroom.udacity.com/nanodegrees/nd114/parts/9754bb98-7654-4656-a82a-6b84f2e292d8/modules/dfa88bde-3589-4372-b72a-ed7a412e2b8d/lessons/b860e3bf-67ea-4a31-9bd6-69ac3fed257c/concepts/0823d7d2-f3b1-4d74-8768-850697f80efd) lesson node.

**Comment by mazurick** [comment]
Hello, 

I know there is a script there, however, I want the  complete script. 

The Script there adequately covers the first part of the lesson but it doesn’t provide the solution to the final problem that involves lifting the hat and making the bunny appear with shuffle.

The instructor knows what I’m referring to can I please just get the ‘complete solution to the challenge’



Adam Mazurick

Sent on my iPhone. Please kindly excuse any typos.

**Comment by smile-0yen** [comment]
+1 
In case Udacity thinks this is only from Mazy.
Since there is no review for lessons, it is better for us to have the answer branch so that we can evaluate our own code.

**Comment by martinwilter** [comment]
Thanks for the up-vote, @smile-0yen. Your argument makes sense. We will update here when the suggested addition has been made available.

**Comment by mazurick** [comment]
So am I getting an extension on the completion date?

Sent on my iPhone. Please kindly excuse any typos.

**Comment by martinwilter** [comment]
@mazurick For account related issues, please contact arkit-support@udacity.com.

**Comment by mazurick** [comment]
What ticket number do I reference? 



Adam Mazurick

Sent on my iPhone. Please kindly excuse any typos.

**Comment by martinwilter** [comment]
@mazurick You don’t need a ticket number. Just send an email to arkit-support@udacity.com with your request. Including an explanation as to why an extension on your completion date is warranted might be helpful.

**Comment by mazurick** [comment]
Hello, 

As per my email with Martin I am asking for an extension on my submission timeline because Udacity has not provided the necessary solution Branch and Script. This is a major impediment to my timely completion of the matter. 2 weeks please

This issue is exhaustively documented in the slack channel.

**Comment by martinwilter** [comment]
@mazurick Did you also send this message to the support team at arkit-support@udacity.com? If not, please do so, as we are not able to assist with account related issues such as this here.

**Comment by mazurick** [comment]
Yes, no one has helped me. 



Adam Mazurick

Sent on my iPhone. Please kindly excuse any typos.

**Comment by martinwilter** [comment]
@mazurick Probably because of the weekend. You should hear back from them today or tomorrow, depending on their weekend backlog.

**Comment by mazurick** [comment]
Thank you :)

**Comment by UdacityVM** [comment]
Example Solutions for the shuffle are now included below the check list :)

**Comment by mazurick** [comment]
Thats very-helpful...and the extension?

Adam Mazurick

Sent on my iPhone. Please kindly excuse any typos.

**Comment by martinwilter** [comment]
@mazurick Because this is a public repo meant for reporting and discussing issues related to the content itself, we are not able to assist with account related issues such deadline extension here, but someone from the support team will respond to the email you sent to arkit-support@udacity.com.

**Comment by mazurick** [comment]
I’ve emailed support 5 times! No one has responded! 

I want an extension on my project by virtue of the fact that 1) you didn’t respond to any questions with a period exceeding 8 days! 2) he organization of the course was so poor that support scripts were not made available. having to spend such protracted period of time communicating with customer service has really not enabled me to complete the work within defined period of time. The lack of support clarifying these things has really created a protracted learning curve that I don’t believe I should have to suffer the expense of. If it requires eight days plus to be responded to by customer support you really need to clarify that in the documentation/ literature that is customer facing.

I am expensing your course with my employer and for research. I need to provide a statement of completion with credential.



Adam Mazurick

Sent on my iPhone. Please kindly excuse any typos.

**Comment by martinwilter** [comment]
@mazurick Really sorry to hear about the delay in receiving a response. I just pinged the support team and asked if they can try to prioritize your email ticket. In the meantime, I recommend proceeding with the course and not worry about the completion deadline, I'm confident they will be able to solve the issue to your satisfaction.
