### ISSUE TITLE
Lesson 2 > Section 12: lack of info

### ISSUE THREAD

**Issue by josephinekao** [udacity/arkit-issues#7]

**Comment by josephinekao** [comment]
"In Lesson 2, Section 12 students are given a challenge to code part of the App.

The course material isn’t comprehensive enough to solve the problem... videos are brief with sparse documentation that was written largely by other sources.

I simply do not know enough about these subjects to solve the challenge and need the code used in the video to solve the problem so I may study it."

**Comment by martinwilter** [comment]
Issue appears to relate to the [Let's Build It!](https://classroom.udacity.com/nanodegrees/nd114/parts/9754bb98-7654-4656-a82a-6b84f2e292d8/modules/dfa88bde-3589-4372-b72a-ed7a412e2b8d/lessons/b860e3bf-67ea-4a31-9bd6-69ac3fed257c/concepts/d55b1af9-9916-49b9-bdfe-58625e04e503) lesson node.

**Comment by UdacityVM** [comment]
Solutions for the code have been added.
