### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by junauh** [udacity/arkit-issues#8]
1) No clear guideline in terms of how to pass an object through a portal i.e. throwing a ball
2) Due to lack of guidance (i.e. 1:1 tutorial/ forum/mentorship), I'd like to ask extension of the degree deadline until all the proper supports and guidance is set properly. 

I do not want to lose hopes on ARKIT class, yet. So please do the above, so we as students who , want to, believe in can learn with patience.

**Comment by martinwilter** [comment]
Thanks for the feedback, @junauh, it's very much appreciated.

For account related issues, such as your request for an extension on the graduation deadline, please contact the support team at arkit-support@udacity.com.

**Comment by UdacityVM** [comment]
Hey Junauh, I would recommend taking a look at how the camera is teleported from scene to scene. You can use very similar logic to teleport the an object through a portal.
